apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

transformers:
  - |-
    apiVersion: examples.config.kubernetes.io/v1beta1
    kind: inject-cloud-sql-proxy
    metadata:
      name: inject-cloud-sql-proxy
      annotations:
        config.kubernetes.io/function: |-
          container:
            image: ghcr.io/treyd-io/blog-kustomize-krm-function-demo:main
    spec:
      proxyImage: europe-north1-docker.pkg.dev/treyd-docker-images/main/gce-proxy
      proxyVersion: sha-f2bc7002b5b0da04ef60e797922fd8b0f1a5fc25
      proxyInstances: treyd-staging:europe-north1:treyd-staging-db=tcp:5432
