apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kustomize.treyd.io/cloud-sql-proxy: "true"
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: image1
          name: container1
        - image: image2
          name: container2
---
